export const MOSTRAR_FORMULARIO = "MOSTRAR_FORMULARIO";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const OBTENER_PROYECTO = "OBTENER_PROYECTO";
export const MOSTRAR_ERROR = "MOSTRAR_ERROR";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

export const TAREAS_PROYECTO = "ELIMINAR_PROYECTO";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TAREA = "VALIDAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
